# Generated by Django 5.1.5 on 2025-01-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarksystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='description',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='tags',
            field=models.CharField(max_length=10),
        ),
    ]
