# Generated by Django 5.1.5 on 2025-01-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarksystem', '0004_workspace_alter_bookmark_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user',
            new_name='workspace',
        ),
    ]
