# Generated by Django 5.1.5 on 2025-01-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarksystem', '0006_alter_bookmark_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(default='https://www.example.com', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarksystem.workspace'),
        ),
    ]
